version: '3.7'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/rental
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rental
    ports:
      - '5432:5432'
    volumes:
          - pgdata:/var/lib/postgresql/data
        networks:
          - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: